bashtage/ng-numpy-randomstate

README.md
pcg/core-rng.c
pcg/core-rng.h
pcg/core_rng.pyx
pcg/performance.py
pcg/test_smoke.py

Expose some other core random number generators: gauss, gamma, exponential.
Add plumbing for more rngs in the c file.

ENH: Add additional RNGs

---

randomstate/shims/pcg-64/pcg-64-shim.h
randomstate/src/pcg64-compat/pcg64.c
randomstate/src/pcg64-compat/pcg64.h
randomstate/tests/test_direct.py
randomstate/tests/test_smoke.py
setup.py

Add PCG64 implementation that supports 32bit platforms.
closes #5

ENH: Add rkern's PCG64 implementation

---

randomstate/interface.pyx
randomstate/setup-all.py
randomstate/setup-basic.py
setup.py

Reorder to match mtrand as closely as possible to facilitate comparrisons
Rename core_rng to interface for more meaning

REF: Reorder and rename core_rng

---

randomstate/__init__.py
randomstate/performance.py
randomstate/tests/test_against_numpy.py
randomstate/tests/test_direct.py
randomstate/tests/test_numpy_mt19937_regressions.py
randomstate/tests/test_smoke.py
randomstate/tests/tests_numpy_mt19937.py
setup.py

Reorganize module into individual directories to help with pickling

REF: Reorganize module

---

randomstate/interface.pyx
randomstate/tests/tests_numpy_mt19937.py

Incorporate deprecation changes

UPD: Update code to latest NumPy changes

---

randomstate/aligned_malloc.c
randomstate/aligned_malloc.h
randomstate/aligned_malloc.pxi
randomstate/interface.pyx
randomstate/shims/dSFMT/dSFMT-shim.c
randomstate/shims/dSFMT/dSFMT-shim.h
randomstate/shims/dSFMT/dSFMT.pxi
randomstate/shims/mlfg-1279-861/mlfg-1279-861.pxi
randomstate/shims/mrg32k3a/mrg32k3a.pxi
randomstate/shims/pcg-32/pcg-32.pxi
randomstate/shims/pcg-64/pcg-64-emulated.pxi
randomstate/shims/pcg-64/pcg-64.pxi
randomstate/shims/random-kit/random-kit.pxi
randomstate/shims/xorshift1024/xorshift1024.pxi
randomstate/shims/xorshift128/xorshift128.pxi
setup.py

Add aligned malloc to simplify dSFMT memory allocation
Switch dSFMT to use a buffer interface to improve performance
Update other function to use pointer when setting state

ENH: Add aligned malloc

---

doc/source/entropy.rst
doc/source/index.rst
doc/source/mlfg.rst
randomstate/interface.pyx
randomstate/shims/dSFMT/dSFMT.pxi
randomstate/shims/mrg32k3a/mrg32k3a.pxi
randomstate/shims/pcg-32/pcg-32.pxi
randomstate/shims/pcg-64/pcg-64-docstring.pxi
randomstate/shims/random-kit/random-kit.pxi
randomstate/shims/xorshift1024/xorshift1024.pxi
randomstate/shims/xorshift128/xorshift128.pxi

Add general introduction
Small fixes to documentation
Seperate entropy into a stand alone page

DOC: Improve documentation

---

randomstate/interface.pyx
randomstate/tests/test_smoke.py

Add support for both zigurat and inv method for all normal generators

ENH: Add support fo ziggurat method for all normal

---

randomstate/array_utilities.pxi
randomstate/interface.pyx
randomstate/tests/tests_numpy_mt19937.py
setup.py

Change scalar arrays to return scalars rather than arrays
Matches behavior of upstream NumPy

FIX: Fix behavior with scalar arrays

---

appveyor.yml
compute_mod3.py
setup.py

Use setup to build and install rather than pip to improve output

TST: Improve appveyor build

---

randomstate/interface/dSFMT/dSFMT-shim.h
randomstate/interface/mlfg-1279-861/mlfg-1279-861-shim.h
randomstate/interface/mrg32k3a/mrg32k3a-shim.h
randomstate/interface/pcg-64/pcg-64-shim.h
randomstate/interface/random-kit/random-kit-shim.h
randomstate/interface/xorshift1024/xorshift1024-shim.h
randomstate/interface/xorshift128/xorshift128-shim.h
randomstate/src/dSFMT/dSFMT.h
randomstate/src/mlfg-1279-861/mlfg-1279-861.h
randomstate/src/mrg32k3a/mrg32k3a.h
randomstate/src/pcg/pcg32.h
randomstate/src/pcg64-compat/pcg64.h
randomstate/src/random-kit/random-kit.h
randomstate/src/splitmix64/splitmix64.h
randomstate/src/xorshift1024/xorshift1024.h
randomstate/src/xorshift128/xorshift128.h
setup.py

Add compile flags for Windows to change inline behavior
Force inlining

BLD: Change inline behavior on Windows

---

randomstate/distributions.h
randomstate/interface/dSFMT/dSFMT-shim.h
randomstate/interface/pcg-32/pcg-32-shim.h
randomstate/interface/pcg-64/pcg-64-shim.h
randomstate/interface/random-kit/random-kit-shim.c
randomstate/interface/random-kit/random-kit-shim.h
randomstate/interface/random-kit/random-kit.pxi
randomstate/randomstate.pyx
randomstate/src/random-kit/random-kit-test-gen.c
randomstate/src/random-kit/random-kit.c
randomstate/src/random-kit/random-kit.h
setup.py

Change randomkit to not overlap wiht numpy functions
Remove erroneous prototype with rk_ prefix
Remove unneeded RNG_TYPE defs

REF: Refactor randomkit

---

randomstate/bounded_integers.pxi
randomstate/randomstate.pyx
randomstate/tests/tests_numpy_mt19937.py

Enfore dtype
Add tests for dtype
Docstring changes

UPD: Sync with recent NumPy changes

---

randomstate/array_utilities.pxi
randomstate/bounded_integers.pxi
randomstate/distributions.c
randomstate/distributions.h
randomstate/interface/dSFMT/dSFMT-shim.h
randomstate/randomstate.pyx

Docstring changes from upstream
Ensure lock used whenever a random number is generated
Change boolean types
Fix bug in dSFMT raw which returned pointer instead of value

UPD: Update to latest NumPy changes

---

randomstate/interface/random-kit/random-kit.pxi
randomstate/randomstate.pyx

Update docstring to reflect changes in upstream NumPy

UPD: Update docstring to latest NumPy

---

randomstate/randomstate.pyx
randomstate/tests/test_smoke.py

Add version to state as a first step to a versioned RandomState

ENH: Add version to state

---

.travis.yml
README.md

Update Readme with performance numbers
Fix small typos
Ensure README and travis agree on what is being tested

DOC: Update Readme

---

README.md
README.rst
randomstate/distributions.c
randomstate/distributions.h
randomstate/interface/dSFMT/dSFMT-shim.h
randomstate/interface/dSFMT/dSFMT.pxi
randomstate/interface/mlfg-1279-861/mlfg-1279-861-shim.h
randomstate/interface/mlfg-1279-861/mlfg-1279-861.pxi
randomstate/interface/mrg32k3a/mrg32k3a-shim.h
randomstate/interface/mrg32k3a/mrg32k3a.pxi
randomstate/interface/pcg-32/pcg-32-shim.h
randomstate/interface/pcg-32/pcg-32.pxi
randomstate/interface/pcg-64/pcg-64-emulated.pxi
randomstate/interface/pcg-64/pcg-64-shim.h
randomstate/interface/pcg-64/pcg-64.pxi
randomstate/interface/random-kit/random-kit-shim.h
randomstate/interface/random-kit/random-kit.pxi
randomstate/interface/xoroshiro128plus/xoroshiro128plus-shim.h
randomstate/interface/xoroshiro128plus/xoroshiro128plus.pxi
randomstate/interface/xorshift1024/xorshift1024-shim.h
randomstate/interface/xorshift1024/xorshift1024.pxi
randomstate/interface/xorshift128/xorshift128-shim.h
randomstate/interface/xorshift128/xorshift128.pxi
randomstate/randomstate.pyx

Augment state to handle 32-bit float normals
Implement pure-32-bit version of normal
Re-factor standard_gamma
Add 32-bit gamma in C

ENH: Add 32-bit normals using Box-Muller

---

appveyor.yml

Update clone depth to avoid issues with fast pushes

TST: Update clone history

---

randomstate/array_utilities.pxi
randomstate/distributions.c
randomstate/randomstate.pyx
randomstate/tests/test_numpy_mt19937_regressions.py
randomstate/tests/tests_numpy_mt19937.py

Ass support for 0 scale inputs swapping CONS_POSITIVE for CONS_NON_NEGATIVE
Add support for -0. arguments
Fix bug in shuffle
Add reference for core Poisson RNG

ENH: Update to latest NumPy additions

---

doc/source/change-log.rst
setup.py

SETUP: Make changes to allow sdist and PyPi to work

---

README.md
README.rst
licenses/NUMPY-LICENSE.rst
randomstate/compat.py
randomstate/randomstate.pyx
randomstate/tests/test_against_numpy.py
randomstate/tests/tests_numpy_mt19937.py

Update code to reflect changes in NumPy's PRNG code

UPD: Update to reflect upstream changes in NumPy

---

README.md
README.rst
doc/source/change-log.rst
doc/source/index.rst
randomstate/array_fillers.pxi.in
randomstate/array_utilities.pxi
randomstate/randomstate.pyx
randomstate/tests/test_smoke.py
randomstate/tests/tests_numpy_mt19937.py

Allow filling existing arrays in standard gamma
Refactor array type checking to avoid dupe code

ENH: Add output support to standard_gamma

---

doc/source/index.rst
doc/source/multithreading.rst

Add documentation showing one methof to fill an array using multiple
threads.
[skip ci]

DOC: Add example of multithreaded filling

---

randomstate/distributions.c
randomstate/randomstate.pyx
randomstate/tests/tests_numpy_mt19937.py

Sync with multivariate normal changes
Change uniform test

SYNC: Sync with upstream changes in NumPy

---

README.md
README.rst
doc/source/change-log.rst
doc/source/conf.py
doc/source/multithreading.rst
randomstate/randomstate.pyx

Fix change log for new release
Typo fixes
[skip ci]

DOC: Doc string fixes

---

README.md
README.rst
doc/source/dsfmt.rst
doc/source/mlfg.rst
doc/source/mrg32k3a.rst
doc/source/mt19937.rst
doc/source/pcg32.rst
doc/source/pcg64.rst
doc/source/xoroshiro128plus.rst
doc/source/xorshift1024.rst
doc/source/xorshift128.rst
randomstate/randomstate.pyx
randomstate/tests/test_numpy_mt19937.py
randomstate/tests/test_smoke.py

Add random uintegers for performance benchmarking

ENH: Readd random uintegers

---

randomstate/array_utilities.pxi

Remove unnecessary python routine use in array_utilities

CLN: Clean up python code in array_utilities

---

randomstate/interface/pcg-64/pcg-64-emulated.pxi
randomstate/randomstate.pyx
randomstate/tests/test_against_numpy.py
randomstate/tests/test_direct.py
randomstate/tests/test_smoke.py

Fix a test which used 3d input instead of the expected 2d.

TST: Fix test input shape

---

randomstate/cython_overrides.pxd
randomstate/tests/test_numpy_mt19937.py

Add changes to upstream tests and protections

TST: Add upstream test changes

---

doc/Makefile
doc/make.bat
doc/source/change-log.rst
doc/source/conf.py
doc/source/dsfmt.rst
doc/source/index.rst
doc/source/mlfg.rst
doc/source/mrg32k3a.rst
doc/source/mt19937.rst
doc/source/pcg32.rst
doc/source/pcg64.rst
doc/source/xoroshiro128plus.rst
doc/source/xorshift1024.rst
doc/source/xorshift128.rst
randomstate/cython_overrides.pxd
randomstate/randomstate.pyx
randomstate/tests/test_smoke.py

Add univariate complex normal distribution

ENH: Add complex normal distribution

---

randomstate/performance.py
randomstate/randomstate.pyx

Add outputles mode for raw to allow accurate performance testing of core
PRNG

ENH: Add output-less mode for raw

---

README.md
README.rst
doc/source/change-log.rst
doc/source/index.rst
randomstate/distributions.c
randomstate/distributions.h
randomstate/randomstate.pyx

Add ziggurat for improve generation of gamma random variables

ENH: Ziggurat for gammas

---

randomstate/tests/test_numpy_mt19937.py

Sync Python types with NumPy types in tests

CLN: Sync with upstream NumPy

---

randomstate/randomstate.pyx
randomstate/tests/test_numpy_mt19937.py

Verify parameters are > 0 as required
Port fo NumPy

BUG: Add check for dirichelet parameters

---

appveyor.yml
doc/source/change-log.rst
randomstate/bounded_integers.pxi.in
randomstate/randomstate.pyx
randomstate/tests/test_smoke.py

Allow array broadcasting for random integers

ENH: Initial work to allow broadcasting

---

randomstate/aligned_malloc.h
randomstate/bounded_integers.pxi.in
randomstate/distributions.c
randomstate/distributions.h
randomstate/randomstate.pyx
setup.py

Simplify bounded integer generators

Simplify bounded int

---

randomstate/distributions.c
randomstate/interface/dSFMT/dSFMT-shim.c
randomstate/interface/dSFMT/dSFMT-shim.h
randomstate/interface/mlfg-1279-861/mlfg-1279-861-shim.c
randomstate/interface/mlfg-1279-861/mlfg-1279-861-shim.h
randomstate/interface/mrg32k3a/mrg32k3a-shim.c
randomstate/interface/mrg32k3a/mrg32k3a-shim.h
randomstate/interface/pcg-32/pcg-32-shim.c
randomstate/interface/pcg-32/pcg-32-shim.h
randomstate/interface/pcg-64/pcg-64-shim.c
randomstate/interface/pcg-64/pcg-64-shim.h
randomstate/interface/random-kit/random-kit-shim.c
randomstate/interface/random-kit/random-kit-shim.h
randomstate/interface/sfmt/sfmt-shim.c
randomstate/interface/sfmt/sfmt-shim.h
randomstate/interface/xoroshiro128plus/xoroshiro128plus-shim.c
randomstate/interface/xoroshiro128plus/xoroshiro128plus-shim.h
randomstate/interface/xorshift1024/xorshift1024-shim.c
randomstate/interface/xorshift1024/xorshift1024-shim.h
randomstate/interface/xorshift128/xorshift128-shim.c
randomstate/interface/xorshift128/xorshift128-shim.h
setup.py

Reformat source files to follow clang styles
Replace inline with NPY_INLINE where viable
Fix missing type declatation in return
Remove install step from Travis

CLN: Reformat source files in interface

---

.travis.yml
randomstate/cython_overrides.pxd
randomstate/interface/sfmt/sfmt-shim.h
randomstate/randomstate.pyx

Use compute complex for DRY pruposes

REF: Use compute complex

---

randomstate/bounded_integers.pxi.in
randomstate/tests/test_numpy_mt19937.py
randomstate/tests/test_numpy_mt19937_regressions.py

Add support for empty return for randint
Refactor tests to avoid testcast
Refactor bounded integers to improve DRY

ENH: Zero element randint

---

.travis.yml
randomstate/interface/mlfg-1279-861/mlfg-1279-861-shim.h
randomstate/interface/mrg32k3a/mrg32k3a-shim.h
randomstate/interface/pcg-32/pcg-32-shim.h
randomstate/interface/pcg-64/pcg-64-shim.h
randomstate/interface/random-kit/random-kit-shim.h
randomstate/interface/xoroshiro128plus/xoroshiro128plus-shim.h
randomstate/interface/xorshift1024/xorshift1024-shim.h
randomstate/interface/xorshift128/xorshift128-shim.h

Declare inline functions as static to prevent errors on some compilers
Fix build to prevent conda errors

Add static

---

ci/docker-run.sh
ci/docker-wheel-build.sh
ci/requirements_dev.txt
randomstate/src/mlfg-1279-861/mlfg-1279-861.h
randomstate/src/mrg32k3a/mrg32k3a.h
randomstate/src/pcg/pcg32.h
randomstate/src/pcg64-compat/pcg64.h
randomstate/src/random-kit/random-kit.h
randomstate/src/xoroshiro128plus/xoroshiro128plus.c
randomstate/src/xoroshiro128plus/xoroshiro128plus.h
randomstate/src/xorshift1024/xorshift1024.h
randomstate/src/xorshift128/xorshift128.h
setup.py

Add static declarations for inline functions
Undefine GNU INLINE flag for manylinux1 build
Add build scripts to simplify wheel building

BLD: Add manylinux1 build

---

doc/source/change-log.rst
randomstate/randomstate.pyx
randomstate/tests/test_numpy_mt19937.py

Sync with latest changes in NumPy

UPD: Update with upstream changes in NumPy

---

randomstate/interface/dSFMT/dSFMT-shim.h

Remove aliasing to prevent warnings

CLN: Remove aliasing

---

.coveragerc
.travis.yml
randomstate/.coveragerc
randomstate/tests/test_numpy_mt19937.py
setup.py

Add line coverage for Cython code

BLD: Add coverage for Cython Code
